version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "10:10"
    timezone: "UTC"

  open-pull-requests-limit: 100

- package-ecosystem: github-actions
  directory: "/"
  schedule: 
    interval: daily
    time: "09:00" # Before submodule update
    timezone: "UTC"