version: "3.6"

services:
 test:
  image: registry.gitlab.com/minetest/minetest/server:${ENGINE_VERSION:-5.7.0}
  user: root
  entrypoint: "minetestserver --config /minetest.conf --gameid 'minetest'"
  volumes:
    - "./:/root/.minetest/mods/"
    - "../minetest_game:/root/.minetest/games/minetest_game/"
    - "../config/world.mt:/root/.minetest/worlds/world/world.mt"
    - "../config/minetest.conf:/minetest.conf"
    - "world:/root/.minetest/worlds/world"

volumes:
  world: {}