version: "3.6"

services:
 test:
  image: registry.gitlab.com/minetest/minetest/server:5.7.0
  user: root
  command: sh -c "chown -r root:root /root/.minetest"
  entrypoint: "minetestserver --config /minetest.conf --gameid 'minetest'"
  volumes:
    - "./mods:/root/.minetest/mods/"
    - "./minetest_game:/root/games/minetest_game/"
    - "./config/minetest.conf:/minetest.conf"
    - "./config/world.mt:/root/.minetest/worlds/world/world.mt"
    - "world:/root/.minetest/worlds/world"

volumes:
  world: {}
