services:
 test:
  image: ${ENGINE_IMAGE:-ghcr.io/minetest/minetest:master}
  user: root
  command: ["--config", "/minetest.conf"]
  volumes:
    - "./:/root/.minetest/mods/"
    - "../minetest_game:/root/.minetest/games/minetest_game/"
    - "../config/world.mt:/root/.minetest/worlds/world/world.mt"
    - "../config/minetest.conf:/minetest.conf"
    - "../world:/root/.minetest/worlds/world"
    - "../archtec_ci:/root/.minetest/worlds/world/worldmods/archtec_ci"