name: integration-test

on: [push]

jobs:
  integrationtest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        ENGINE_IMAGE:
          - registry.gitlab.com/minetest/minetest/server:5.6.1
          - registry.gitlab.com/minetest/minetest/server:5.7.0
          - ghcr.io/minetest-hosting/minetest-docker:5.8.0

    steps:
    - name: Checkout (mods)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        path: mods

    - name: Checkout (minetest_game)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: Archtec-io/minetest_game
        path: minetest_game

    - name: Checkout (config)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: Archtec-io/config
        path: config

    - name: Integration test
      run: docker-compose -f ./mods/docker-compose.yml up --exit-code-from test test