name: merge-forks

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: areas
      run: ./merge.sh
      env:
        repo: areas
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: armor-skins-and-wielditems
      run: ./merge.sh
      env:
        repo: armor-skins-and-wielditems
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: auroras
      run: ./merge.sh
      env:
        repo: auroras
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: choppy
      run: ./merge.sh
      env:
        repo: choppy
        branch: main
        token: ${{ secrets.MERGE_KEY }}

    - name: darkage
      run: ./merge.sh
      env:
        repo: darkage
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: ethereal
      run: ./merge.sh
      env:
        repo: ethereal
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: facade
      run: ./merge.sh
      env:
        repo: facade
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: moreblocks
      run: ./merge.sh
      env:
        repo: moreblocks
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: moretrees
      run: ./merge.sh
      env:
        repo: moretrees
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: mymillwork
      run: ./merge.sh
      env:
        repo: mymillwork
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: pkarcs
      run: ./merge.sh
      env:
        repo: pkarcs
        branch: master
        token: ${{ secrets.MERGE_KEY }}

    - name: xban2
      run: ./merge.sh
      env:
        repo: xban2
        branch: master
        token: ${{ secrets.MERGE_KEY }}